version: '3.8'

services:
  backend:
    image: python:3
    container_name: python-backend
    working_dir: /usr/src/app
    command: make dev
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "8000:8000"

  frontend:
    image: node:23
    container_name: react-frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true # For hot-reloading in Docker
    working_dir: /app
    command: make dev
