# Generated by Django 5.1.2 on 2024-10-26 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('embeddings', models.BinaryField(null=True)),
                ('created_date', models.DateTimeField(verbose_name='record date created')),
                ('updated_date', models.DateTimeField(verbose_name='record date updated')),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('embeddings', models.BinaryField(null=True)),
                ('created_date', models.DateTimeField(verbose_name='record date created')),
                ('updated_date', models.DateTimeField(verbose_name='record date updated')),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('doi', models.CharField(max_length=128, null=True)),
                ('abstract', models.TextField()),
                ('url', models.URLField(null=True)),
                ('embeddings', models.BinaryField()),
                ('published_date', models.DateTimeField(verbose_name='paper date published')),
                ('created_date', models.DateTimeField(verbose_name='record date published')),
                ('updated_date', models.DateTimeField(verbose_name='record date updated')),
                ('authors', models.ManyToManyField(to='papers.author')),
                ('journal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='papers.journal')),
            ],
        ),
        migrations.CreateModel(
            name='PaperDistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField()),
                ('created_date', models.DateTimeField(verbose_name='record date created')),
                ('updated_date', models.DateTimeField(verbose_name='record date updated')),
                ('paper1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_distances_as_paper1', to='papers.paper')),
                ('paper2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_distances_as_paper2', to='papers.paper')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('paper1', 'paper2'), name='unique_paper_pair'), models.UniqueConstraint(fields=('paper2', 'paper1'), name='unique_reverse_paper_pair')],
            },
        ),
    ]
